### ISSUE TITLE
Slightly confusing use case

### ISSUE THREAD

**Issue by artburkart** [CoryNoonan/unix-timestamp-chrome#2]
Long time user, first time issue filer. Love the plugin! Been telling all my coworkers to use it. Today I ran into a slightly confusing use case; not a show stopper by any means, but maybe something to consider.

If you paste a timestamp into the 'Unix Timestamp' input box, then proceed to type in a date in the "enter a date in any format" input box, and click convert, it's not clear which input it is converting for me.

![image](https://cloud.githubusercontent.com/assets/463528/16809532/aaacab7e-48ee-11e6-9718-31f1ed171fac.png)

**Comment by spoonscen** [comment]
@artburkart Sorry for the delay! I just noticed this issue! Must have gotten swallowed by my emails.  What do you think the expected behavior should be?  I am thinking if both boxes have content we can prevent the user from clicking convert?

**Comment by artburkart** [comment]
That seems like a valid and simple solution to me. Should I make a PR?

**Comment by spoonscen** [comment]
That would be great! Thanks Arthur! Once the PR is in and tested there are a few steps to bundle and deploy to google. I'd love to get that enhancement into this!

**Comment by spoonscen** [comment]
Fixed in #7
